### ISSUE TITLE
RESOLVED

### ISSUE THREAD

**Issue by real2two** [Futuristic-Development/FutureBoard-v0.1#1]
https://github.com/Futuristic-Development/FutureBoard-v1/blob/main/LICENSE

I'm fine with you forking my project, but you can't just change the copyright. That's illegal.

**Comment by real2two** [comment]
i'm gonna give you 2 weeks to change back the original license. (ofc you can sublicense but you can't remove the original one)

**Comment by Xmomoo** [comment]
Futureboard is good

**Comment by Joseph-futuristic** [comment]
> https://github.com/Futuristic-Development/FutureBoard-v1/blob/main/LICENSE
> 
> I'm fine with you forking my project, but you can't just change the copyright. That's illegal.

done

**Comment by Joseph-futuristic** [comment]
I will be locking this conversation please contact me on discord "Joseph_#6390" if you looking to say anything more!
