### ISSUE TITLE
Remove my name from your Project - Resolved

### ISSUE THREAD

**Issue by kittensaredabest** [Futuristic-Development/FutureBoard-v0.1#3]
In the file https://github.com/Futuristic-Development/FutureBoard-v0.1/blob/main/themes/default/index.ejs 

It has my Discord username ( MythicalKitten#0001 ) listed in the credits of the project

I am no way associated with said project and I have not touched this project (FutureBoard) at all. So I request that you remove my name from your project

**Comment by snaildos** [comment]
@Joseph-futuristic #5 
Merge the PR to remove Mythical from credits.

**Comment by snaildos** [comment]
@Joseph-futuristic I deleted the PR so I don't become a contributor. Please kindly remove it.

**Comment by Joseph-futuristic** [comment]
Done :)
